version: '3.7'

services:
  db:
    image: postgres:11.3
  web:
    labels:
      com.marekfs.name: "Marek Siekierski"
      com.marekfs.email: "mark.siekierski@gmail.com"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - node
  node:
    build: docker/node
    environment:
      - NODE_ENV=production
    volumes:
      - ./static:/home/node/app
    command: /usr/local/bin/startup.sh
